### ISSUE TITLE
语音添加（广播剧-プロローグ）

### ISSUE THREAD

**Issue by lzw-723** [syang-ng/Yuigahama-Yui-rainbow-fart#2]
[Yuigahama-Yui-add.zip](https://github.com/syang-ng/Yuigahama-Yui-rainbow-fart/files/4839982/Yuigahama-Yui-add.zip)
从广播剧里剪了几句出来，不知道能不能帮上忙
[广播剧](http://music.163.com/m/playlist?id=2520417052&userid=1569932860)

**Comment by syang-ng** [comment]
感谢！素材文件已经添加到最新的语音包中！
